export const caseStudies = [
  {
    id:      'design-ops',
    index:   '01',
    title:   'Building a Design Operations Function from the Ground Up',
    company: 'Plexus Worldwide',
    year:    '2026',
    outcome: 'Consolidated 6 fragmented tools into a unified design system, cutting team inefficiency by 60% and increasing sprint delivery velocity by 35%.',
    tags:    ['Design Ops', 'Systems Thinking', 'Team Leadership', 'AI Tooling'],
    color:   '#3B82F6',
    href:    'https://www.uxapex.com/designops',
  },
  {
    id:      'plexus-ecomm',
    index:   '02',
    title:   'E-Commerce Modernization: From Friction to Conversion',
    company: 'Plexus Worldwide',
    year:    '2026',
    outcome: 'Redesigned the complete e-commerce experience across US and 3 international regions — reducing checkout abandonment by 43% through data-driven UX and mobile-first design.',
    tags:    ['e-Commerce', 'UX Strategy', 'Mobile-First', 'A/B Testing'],
    color:   '#FF6B35',
    href:    'https://www.uxapex.com/ecomm',
  },
  {
    id:      'ux-transformation',
    index:   '03',
    title:   'Leading a Company-Wide UX Transformation',
    company: 'Multi-Company · 2021–2026',
    year:    '2021–2026',
    outcome: 'Elevated design from a service function to a strategic driver — securing C-suite buy-in and delivering measurable outcomes across e-commerce, mining, and self-storage.',
    tags:    ['UX Strategy', 'Executive Influence', 'Cross-Functional', 'Workshops'],
    color:   '#8B5CF6',
    href:    'https://www.uxapex.com/uxtrans',
  },
  {
    id:      'Executive Industry Action',
    index:   '04',
    title:   'Rise of AI suggestions | How Discovery is Evolving ',
    company: 'Industry Wide',
    year:    '2026',
    outcome: 'Products, Companies, and online experiences like web apps and digital products are being left out of discovery from users LLM use. Those who adapt will have longer competitive gains verse delaying.',
    tags:    ['Consumer LLM use', 'Discover Experience', 'AI Strategy'],
    color:   '#10B981',
    href:    'https://www.uxapex.com/discovery',
  },
  {
    id:      'E-commerce Persona Generator',
    index:   '05',
    title:   'Getting quality from quantity | Scaling Revenue Generator from Behavorial Metrics',
    company: 'E-commerce • Retail',
    year:    '2025 - 2026',
    outcome: 'Enabled the organization to operate as a coordinated, insight-driven engine to optimize the performance of brand discovery, member expansion, and subsciption volumes.',
    tags:    ['Quality in = quality out', 'Systems Governance', 'Cross Functional Strategy'],
    color:   '#FFC300',
    href:    'https://www.uxapex.com/persona',
  },
   {
    id:      'Maturity through onboarding Methodologies',
    index:   '06',
    title:   'Scaling Company Efforts | Delivering and Shipping Outcomes Faster',
    company: 'Design Operations • Optimizing workflows, tools, and team culture',
    year:    '2025',
    outcome: 'A unified "source of truth" that creates bi-lateral accountability, ensures consistency of a product, and improves communications between design, engineering, product, and business units.',
    tags:    ['Start with quality = End with quality', 'Product Governance', 'Cross Functional Accountability'],
    color:   '#E00004',
    href:    'https://www.uxapex.com/collaboration',
  },
]
